CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(50) NOT NULL,
    name  VARCHAR(50) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id            BIGINT        NOT NULL, -- Id пользователя инициатора
    annotation         VARCHAR(2000) NOT NULL, -- Краткое описание события
    category_id        BIGINT        NOT NULL, -- Id категории к которой относится событие
    confirmed_requests INT,                    -- Количество одобренных заявок
    created_on         TIMESTAMP,              -- Дата и время создания события
    description        VARCHAR(7000) NOT NULL, -- Полное описание события
    event_date         TIMESTAMP     NOT NULL, -- Дата и время на которые намечено событие.
    location_lat       REAL          NOT NULL, -- Широта места проведения события
    location_lon       REAL          NOT NULL, -- Долгота места проведения события
    paid               BOOLEAN DEFAULT FALSE,  -- Оплата участие в событии
    participant_limit  INT     DEFAULT 0,      -- Ограничение на количество участников.
    published_on       TIMESTAMP,              -- Дата и время публикации события
    available          BOOLEAN DEFAULT TRUE,   -- Доступность для участия
    request_moderation BOOLEAN DEFAULT TRUE,   -- Модерация заявок на участие
    title              VARCHAR(120)  NOT NULL, -- Заголовок события
    state              VARCHAR(10)   NOT NULL, -- Состояний жизненного цикла события (PENDING, PUBLISHED, CANCELED)
    views              INT     DEFAULT 0,      -- Количество просмотрев события
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT fk_event__users FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_event__categories FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE IF NOT EXISTS participation_request
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY, -- Идентификатор заявки
    created      TIMESTAMP NOT NULL,                      -- Дата и время создания заявки
    event_id     BIGINT,                                  -- Идентификатор события
    requester_id BIGINT,                                  -- Идентификатор пользователя, отправившего заявку
    status       VARCHAR(20),                             -- Статус заявки
    CONSTRAINT pk_participation_request PRIMARY KEY (id),
    CONSTRAINT fk_participation_request__users FOREIGN KEY (requester_id) REFERENCES users (id),
    CONSTRAINT uq_requester_event UNIQUE (event_id, requester_id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY, -- Идентификатор подборки
    pinned BOOLEAN DEFAULT FALSE,                   -- Закреплена ли подборка на главной странице сайта
    title  VARCHAR(100) NOT NULL,                   -- Заголовок подборки
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    event_id        BIGINT NOT NULL,
    compilations_id BIGINT NOT NULL,
    PRIMARY KEY (event_id, compilations_id)
);

CREATE TABLE IF NOT EXISTS rating_events
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT  NOT NULL,
    event_id   BIGINT  NOT NULL,
    like_event BOOLEAN NOT NULL,
    CONSTRAINT pk_rating_events PRIMARY KEY (user_id, event_id),
    CONSTRAINT fk_rating_events__users FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_rating_events__events FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT uq_rating_events UNIQUE (user_id, event_id)
);
