CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(50) NOT NULL,
    name  VARCHAR(50) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name  VARCHAR(50) NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS ewent
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY ,
    user_id BIGINT NOT NULL ,
    annotation VARCHAR(2000) NOT NULL ,
    category_id BIGINT NOT NULL ,
    description VARCHAR(7000) NOT NULL ,
    eventDate TIMESTAMP NOT NULL ,
    location_lat REAL NOT NULL,
    location_lon REAL NOT NULL,
    paid BOOLEAN DEFAULT FALSE,
    participantLimit INT DEFAULT 0,
    requestModeration BOOLEAN DEFAULT TRUE,
    title VARCHAR(120) NOT NULL ,
    CONSTRAINT pk_ewent PRIMARY KEY (id),
    CONSTRAINT fk_ewent_users FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_ewent_categories FOREIGN KEY (category_id) REFERENCES categories(id)
);